#include "visulizer.h"
#include <util/log.h>
#include <core/spirvdefines.h>

using namespace thc;
using namespace core;
using namespace visualizer;
using namespace utils;

static char* opCodeString[1024];

#define PAIR(op) opCodeString[op] = ThingaMaBob(#op)

static char* ThingaMaBob(const char* string) {
	uint64 len = strlen(string) - 16;

	char* str = new char[len];
	memcpy(str, string + 17, len);

	return str;
}

static void InitializeOpCodes() {
	for (uint32 i = 0; i < 1024; i++) {
		opCodeString[i] = "Unknown";
	}

	PAIR(THC_SPIRV_OPCODE_OpNop);
	PAIR(THC_SPIRV_OPCODE_OpUndef);
	PAIR(THC_SPIRV_OPCODE_OpSizeOf);
	PAIR(THC_SPIRV_OPCODE_OpSourceContinued);
	PAIR(THC_SPIRV_OPCODE_OpSource);
	PAIR(THC_SPIRV_OPCODE_OpSourceExtension);
	PAIR(THC_SPIRV_OPCODE_OpName);
	PAIR(THC_SPIRV_OPCODE_OpMemberName);
	PAIR(THC_SPIRV_OPCODE_OpString);
	PAIR(THC_SPIRV_OPCODE_OpLine);
	PAIR(THC_SPIRV_OPCODE_OpNoLine);
	PAIR(THC_SPIRV_OPCODE_OpDecorate);
	PAIR(THC_SPIRV_OPCODE_OpMemberDecorate);
	PAIR(THC_SPIRV_OPCODE_OpDecorateGroup);
	PAIR(THC_SPIRV_OPCODE_OpGroupDecorate);
	PAIR(THC_SPIRV_OPCODE_OpGroupMemberDecorate);
	PAIR(THC_SPIRV_OPCODE_OpDecorateId);
	PAIR(THC_SPIRV_OPCODE_OpExtension);
	PAIR(THC_SPIRV_OPCODE_OpExtInstImport);
	PAIR(THC_SPIRV_OPCODE_OpExtInst);
	PAIR(THC_SPIRV_OPCODE_OpMemoryModel);
	PAIR(THC_SPIRV_OPCODE_OpEntryPoint);
	PAIR(THC_SPIRV_OPCODE_OpExecutionMode);
	PAIR(THC_SPIRV_OPCODE_OpCapability);
	PAIR(THC_SPIRV_OPCODE_OpExecutionModeId);
	PAIR(THC_SPIRV_OPCODE_OpTypeVoid);
	PAIR(THC_SPIRV_OPCODE_OpTypeBool);
	PAIR(THC_SPIRV_OPCODE_OpTypeInt);
	PAIR(THC_SPIRV_OPCODE_OpTypeFloat);
	PAIR(THC_SPIRV_OPCODE_OpTypeVector);
	PAIR(THC_SPIRV_OPCODE_OpTypeMatrix);
	PAIR(THC_SPIRV_OPCODE_OpTypeImage);
	PAIR(THC_SPIRV_OPCODE_OpTypeSampler);
	PAIR(THC_SPIRV_OPCODE_OpTypeSampledImage);
	PAIR(THC_SPIRV_OPCODE_OpTypeArray);
	PAIR(THC_SPIRV_OPCODE_OpTypeRuntimeArray);
	PAIR(THC_SPIRV_OPCODE_OpTypeStruct);
	PAIR(THC_SPIRV_OPCODE_OpTypeOpaque);
	PAIR(THC_SPIRV_OPCODE_OpTypePointer);
	PAIR(THC_SPIRV_OPCODE_OpTypeFunction);
	PAIR(THC_SPIRV_OPCODE_OpTypeEvent);
	PAIR(THC_SPIRV_OPCODE_OpTypeDeviceEvent);
	PAIR(THC_SPIRV_OPCODE_OpTypeReserveId);
	PAIR(THC_SPIRV_OPCODE_OpTypeQueue);
	PAIR(THC_SPIRV_OPCODE_OpTypePipe);
	PAIR(THC_SPIRV_OPCODE_OpTypeForwardPointer);
	PAIR(THC_SPIRV_OPCODE_OpTypePipeStorage);
	PAIR(THC_SPIRV_OPCODE_OpTypeNamedBarrier);
	PAIR(THC_SPIRV_OPCODE_OpConstantTrue);
	PAIR(THC_SPIRV_OPCODE_OpConstantFalse);
	PAIR(THC_SPIRV_OPCODE_OpConstant);
	PAIR(THC_SPIRV_OPCODE_OpConstantComposite);
	PAIR(THC_SPIRV_OPCODE_OpConstantSampler);
	PAIR(THC_SPIRV_OPCODE_OpConstantNull);
	PAIR(THC_SPIRV_OPCODE_OpSpecConstantTrue);
	PAIR(THC_SPIRV_OPCODE_OpSpecConstantFalse);
	PAIR(THC_SPIRV_OPCODE_OpSpecConstant);
	PAIR(THC_SPIRV_OPCODE_OpSpecConstantComposite);
	PAIR(THC_SPIRV_OPCODE_OpSpecConstantOp);
	PAIR(THC_SPIRV_OPCODE_OpVariable);
	PAIR(THC_SPIRV_OPCODE_OpImageTexelPointer);
	PAIR(THC_SPIRV_OPCODE_OpLoad);
	PAIR(THC_SPIRV_OPCODE_OpStore);
	PAIR(THC_SPIRV_OPCODE_OpCopyMemory);
	PAIR(THC_SPIRV_OPCODE_OpCopyMemorySized);
	PAIR(THC_SPIRV_OPCODE_OpAccessChain);
	PAIR(THC_SPIRV_OPCODE_OpInBoundsAccessChain);
	PAIR(THC_SPIRV_OPCODE_OpPtrAccessChain);
	PAIR(THC_SPIRV_OPCODE_OpArrayLength);
	PAIR(THC_SPIRV_OPCODE_OpGenericPtrMemSemantics);
	PAIR(THC_SPIRV_OPCODE_OpInBoundsPtrAccessChain);
	PAIR(THC_SPIRV_OPCODE_OpFunction);
	PAIR(THC_SPIRV_OPCODE_OpFunctionParameter);
	PAIR(THC_SPIRV_OPCODE_OpFunctionEnd);
	PAIR(THC_SPIRV_OPCODE_OpFunctionCall);
	PAIR(THC_SPIRV_OPCODE_OpSampledImage);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleDrefImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleDrefExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleProjImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleProjExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleProjDrefImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSampleProjDrefExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageFetch);
	PAIR(THC_SPIRV_OPCODE_OpImageGather);
	PAIR(THC_SPIRV_OPCODE_OpImageDrefGather);
	PAIR(THC_SPIRV_OPCODE_OpImageRead);
	PAIR(THC_SPIRV_OPCODE_OpImageWrite);
	PAIR(THC_SPIRV_OPCODE_OpImage);
	PAIR(THC_SPIRV_OPCODE_OpImageQueryFormat);
	PAIR(THC_SPIRV_OPCODE_OpImageQueryOrder);
	PAIR(THC_SPIRV_OPCODE_OpImageQuerySizeLod);
	PAIR(THC_SPIRV_OPCODE_OpImageQuerySize);
	PAIR(THC_SPIRV_OPCODE_OpImageQueryLod);
	PAIR(THC_SPIRV_OPCODE_OpImageQueryLevels);
	PAIR(THC_SPIRV_OPCODE_OpImageQuerySamples);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleDrefImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleDrefExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleProjImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleProjExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleProjDrefImplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseSampleProjDrefExplicitLod);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseFetch);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseGather);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseDrefGather);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseTexelsResident);
	PAIR(THC_SPIRV_OPCODE_OpImageSparseRead);
	PAIR(THC_SPIRV_OPCODE_OpConvertFToU);
	PAIR(THC_SPIRV_OPCODE_OpConvertFToS);
	PAIR(THC_SPIRV_OPCODE_OpConvertSToF);
	PAIR(THC_SPIRV_OPCODE_OpConvertUToF);
	PAIR(THC_SPIRV_OPCODE_OpUConvert);
	PAIR(THC_SPIRV_OPCODE_OpSConvert);
	PAIR(THC_SPIRV_OPCODE_OpFConvert);
	PAIR(THC_SPIRV_OPCODE_OpQuantizeToF16);
	PAIR(THC_SPIRV_OPCODE_OpConvertPtrToU);
	PAIR(THC_SPIRV_OPCODE_OpSatConvertSToU);
	PAIR(THC_SPIRV_OPCODE_OpSatConvertUToS);
	PAIR(THC_SPIRV_OPCODE_OpConvertUToPtr);
	PAIR(THC_SPIRV_OPCODE_OpPtrCastToGeneric);
	PAIR(THC_SPIRV_OPCODE_OpGenericCastToPtr);
	PAIR(THC_SPIRV_OPCODE_OpGenericCastToPtrExplicit);
	PAIR(THC_SPIRV_OPCODE_OpBitcast);
	PAIR(THC_SPIRV_OPCODE_OpVectorExtractDynamic);
	PAIR(THC_SPIRV_OPCODE_OpVectorInsertDynamic);
	PAIR(THC_SPIRV_OPCODE_OpVectorShuffle);
	PAIR(THC_SPIRV_OPCODE_OpCompositeConstruct);
	PAIR(THC_SPIRV_OPCODE_OpCompositeExtract);
	PAIR(THC_SPIRV_OPCODE_OpCompositeInsert);
	PAIR(THC_SPIRV_OPCODE_OpCopyObject);
	PAIR(THC_SPIRV_OPCODE_OpTranspose);
	PAIR(THC_SPIRV_OPCODE_OpSNegate);
	PAIR(THC_SPIRV_OPCODE_OpFNegate);
	PAIR(THC_SPIRV_OPCODE_OpIAdd);
	PAIR(THC_SPIRV_OPCODE_OpFAdd);
	PAIR(THC_SPIRV_OPCODE_OpISub);
	PAIR(THC_SPIRV_OPCODE_OpFSub);
	PAIR(THC_SPIRV_OPCODE_OpIMul);
	PAIR(THC_SPIRV_OPCODE_OpFMul);
	PAIR(THC_SPIRV_OPCODE_OpUDiv);
	PAIR(THC_SPIRV_OPCODE_OpSDiv);
	PAIR(THC_SPIRV_OPCODE_OpFDiv);
	PAIR(THC_SPIRV_OPCODE_OpUMod);
	PAIR(THC_SPIRV_OPCODE_OpSRem);
	PAIR(THC_SPIRV_OPCODE_OpSMod);
	PAIR(THC_SPIRV_OPCODE_OpFRem);
	PAIR(THC_SPIRV_OPCODE_OpFMod);
	PAIR(THC_SPIRV_OPCODE_OpVectorTimesScalar);
	PAIR(THC_SPIRV_OPCODE_OpMatrixTimesScalar);
	PAIR(THC_SPIRV_OPCODE_OpVectorTimesMatrix);
	PAIR(THC_SPIRV_OPCODE_OpMatrixTimesVector);
	PAIR(THC_SPIRV_OPCODE_OpMatrixTimesMatrix);
	PAIR(THC_SPIRV_OPCODE_OpOuterProduct);
	PAIR(THC_SPIRV_OPCODE_OpDot);
	PAIR(THC_SPIRV_OPCODE_OpIAddCarry);
	PAIR(THC_SPIRV_OPCODE_OpISubBorrow);
	PAIR(THC_SPIRV_OPCODE_OpUMulExtended);
	PAIR(THC_SPIRV_OPCODE_OpSMulExtended);
	PAIR(THC_SPIRV_OPCODE_OpShiftRightLogical);
	PAIR(THC_SPIRV_OPCODE_OpShiftRightArithmetic);
	PAIR(THC_SPIRV_OPCODE_OpShiftLeftLogical);
	PAIR(THC_SPIRV_OPCODE_OpBitwiseOr);
	PAIR(THC_SPIRV_OPCODE_OpBitwiseXor);
	PAIR(THC_SPIRV_OPCODE_OpBitwiseAnd);
	PAIR(THC_SPIRV_OPCODE_OpNot);
	PAIR(THC_SPIRV_OPCODE_OpBitFieldInsert);
	PAIR(THC_SPIRV_OPCODE_OpBitFieldSExtract);
	PAIR(THC_SPIRV_OPCODE_OpBitFieldUExtract);
	PAIR(THC_SPIRV_OPCODE_OpBitReverse);
	PAIR(THC_SPIRV_OPCODE_OpBitCount);
	PAIR(THC_SPIRV_OPCODE_OpAny);
	PAIR(THC_SPIRV_OPCODE_OpAll);
	PAIR(THC_SPIRV_OPCODE_OpIsNan);
	PAIR(THC_SPIRV_OPCODE_OpIsInf);
	PAIR(THC_SPIRV_OPCODE_OpIsFinite);
	PAIR(THC_SPIRV_OPCODE_OpIsNormal);
	PAIR(THC_SPIRV_OPCODE_OpSignBitSet);
	PAIR(THC_SPIRV_OPCODE_OpLessOrGreater);
	PAIR(THC_SPIRV_OPCODE_OpOrdered);
	PAIR(THC_SPIRV_OPCODE_OpUnordered);
	PAIR(THC_SPIRV_OPCODE_OpLogicalEqual);
	PAIR(THC_SPIRV_OPCODE_OpLogicalNotEqual);
	PAIR(THC_SPIRV_OPCODE_OpLogicalOr);
	PAIR(THC_SPIRV_OPCODE_OpLogicalAnd);
	PAIR(THC_SPIRV_OPCODE_OpLogicalNot);
	PAIR(THC_SPIRV_OPCODE_OpSelect);
	PAIR(THC_SPIRV_OPCODE_OpIEqual);
	PAIR(THC_SPIRV_OPCODE_OpINotEqual);
	PAIR(THC_SPIRV_OPCODE_OpUGreaterThan);
	PAIR(THC_SPIRV_OPCODE_OpSGreaterThan);
	PAIR(THC_SPIRV_OPCODE_OpUGreaterThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpSGreaterThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpULessThan);
	PAIR(THC_SPIRV_OPCODE_OpSLessThan);
	PAIR(THC_SPIRV_OPCODE_OpULessThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpSLessThanEqual); 
	PAIR(THC_SPIRV_OPCODE_OpFOrdEqual);	   
	PAIR(THC_SPIRV_OPCODE_OpFUnordEqual);
	PAIR(THC_SPIRV_OPCODE_OpFOrdNotEqual);
	PAIR(THC_SPIRV_OPCODE_OpFUnordNotEqual);
	PAIR(THC_SPIRV_OPCODE_OpFOrdLessThan);
	PAIR(THC_SPIRV_OPCODE_OpFUnordLessThan);
	PAIR(THC_SPIRV_OPCODE_OpFOrdGreaterThan);
	PAIR(THC_SPIRV_OPCODE_OpFUnordGreaterThan);
	PAIR(THC_SPIRV_OPCODE_OpFOrdLessThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpFUnordLessThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpFOrdGreaterThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpFUnordGreaterThanEqual);
	PAIR(THC_SPIRV_OPCODE_OpDPdx);
	PAIR(THC_SPIRV_OPCODE_OpDPdy);
	PAIR(THC_SPIRV_OPCODE_OpFwidth);
	PAIR(THC_SPIRV_OPCODE_OpDPdxFine);
	PAIR(THC_SPIRV_OPCODE_OpDPdyFine);
	PAIR(THC_SPIRV_OPCODE_OpFwidthFine);
	PAIR(THC_SPIRV_OPCODE_OpDPdxCoarse);
	PAIR(THC_SPIRV_OPCODE_OpDPdyCoarse);
	PAIR(THC_SPIRV_OPCODE_OpFwidthCoarse);
	PAIR(THC_SPIRV_OPCODE_OpPhi);
	PAIR(THC_SPIRV_OPCODE_OpLoopMerge);
	PAIR(THC_SPIRV_OPCODE_OpSelectionMerge);
	PAIR(THC_SPIRV_OPCODE_OpLabel);
	PAIR(THC_SPIRV_OPCODE_OpBranch);
	PAIR(THC_SPIRV_OPCODE_OpBranchConditional);
	PAIR(THC_SPIRV_OPCODE_OpSwitch);
	PAIR(THC_SPIRV_OPCODE_OpKill);
	PAIR(THC_SPIRV_OPCODE_OpReturn);
	PAIR(THC_SPIRV_OPCODE_OpReturnValue);
	PAIR(THC_SPIRV_OPCODE_OpUnreachable);
	PAIR(THC_SPIRV_OPCODE_OpLifetimeStart);
	PAIR(THC_SPIRV_OPCODE_OpLifetimeStop);
	PAIR(THC_SPIRV_OPCODE_OpAtomicLoad);
	PAIR(THC_SPIRV_OPCODE_OpAtomicStore);
	PAIR(THC_SPIRV_OPCODE_OpAtomicExchange);
	PAIR(THC_SPIRV_OPCODE_OpAtomicCompareExchange);
	PAIR(THC_SPIRV_OPCODE_OpAtomicCompareExchangeWeak);
	PAIR(THC_SPIRV_OPCODE_OpAtomicIIncrement);
	PAIR(THC_SPIRV_OPCODE_OpAtomicIDecrement);
	PAIR(THC_SPIRV_OPCODE_OpAtomicIAdd);
	PAIR(THC_SPIRV_OPCODE_OpAtomicISub);
	PAIR(THC_SPIRV_OPCODE_OpAtomicSMin);
	PAIR(THC_SPIRV_OPCODE_OpAtomicUMin);
	PAIR(THC_SPIRV_OPCODE_OpAtomicSMax);
	PAIR(THC_SPIRV_OPCODE_OpAtomicUMax);
	PAIR(THC_SPIRV_OPCODE_OpAtomicAnd);
	PAIR(THC_SPIRV_OPCODE_OpAtomicOr);
	PAIR(THC_SPIRV_OPCODE_OpAtomicXor);
	PAIR(THC_SPIRV_OPCODE_OpAtomicFlagTestAndSet);
	PAIR(THC_SPIRV_OPCODE_OpAtomicFlagClear);
	PAIR(THC_SPIRV_OPCODE_OpEmitVertex);
	PAIR(THC_SPIRV_OPCODE_OpEndPrimitive);
	PAIR(THC_SPIRV_OPCODE_OpEmitStreamVertex);
	PAIR(THC_SPIRV_OPCODE_OpEndStreamPrimitive);
	PAIR(THC_SPIRV_OPCODE_OpControlBarrier);
	PAIR(THC_SPIRV_OPCODE_OpMemoryBarrier);
	PAIR(THC_SPIRV_OPCODE_OpNamedBarrierInitialize);
	PAIR(THC_SPIRV_OPCODE_OpMemoryNamedBarrier);
	PAIR(THC_SPIRV_OPCODE_OpGroupAsyncCopy);
	PAIR(THC_SPIRV_OPCODE_OpGroupWaitEvents);
	PAIR(THC_SPIRV_OPCODE_OpGroupAll);
	PAIR(THC_SPIRV_OPCODE_OpGroupAny);
	PAIR(THC_SPIRV_OPCODE_OpGroupBroadcast);
	PAIR(THC_SPIRV_OPCODE_OpGroupIAdd);
	PAIR(THC_SPIRV_OPCODE_OpGroupFAdd);
	PAIR(THC_SPIRV_OPCODE_OpGroupFMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupUMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupSMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupFMax);
	PAIR(THC_SPIRV_OPCODE_OpGroupUMax);
	PAIR(THC_SPIRV_OPCODE_OpGroupSMax);
	PAIR(THC_SPIRV_OPCODE_OpEnqueueMarker);
	PAIR(THC_SPIRV_OPCODE_OpEnqueueKernel);
	PAIR(THC_SPIRV_OPCODE_OpGetKernelNDrangeSubGroupCount);
	PAIR(THC_SPIRV_OPCODE_OpGetKernelNDrangeMaxSubGroupSize);
	PAIR(THC_SPIRV_OPCODE_OpGetKernelPreferredWorkGroupSizeMultiple);
	PAIR(THC_SPIRV_OPCODE_OpRetainEvent);
	PAIR(THC_SPIRV_OPCODE_OpReleaseEvent);
	PAIR(THC_SPIRV_OPCODE_OpCreateUserEvent);
	PAIR(THC_SPIRV_OPCODE_OpIsValidEvent);
	PAIR(THC_SPIRV_OPCODE_OpSetUserEventStatus);
	PAIR(THC_SPIRV_OPCODE_OpCaptureEventProfilingInfo);
	PAIR(THC_SPIRV_OPCODE_OpGetDefaultQueue);
	PAIR(THC_SPIRV_OPCODE_OpBuildNDRange);
	PAIR(THC_SPIRV_OPCODE_OpGetKernelLocalSizeForSubgroupCount);
	PAIR(THC_SPIRV_OPCODE_OpGetKernelMaxNumSubgroups);
	PAIR(THC_SPIRV_OPCODE_OpReadPipe);
	PAIR(THC_SPIRV_OPCODE_OpWritePipe);
	PAIR(THC_SPIRV_OPCODE_OpReservedReadPipe);
	PAIR(THC_SPIRV_OPCODE_OpReservedWritePipe);
	PAIR(THC_SPIRV_OPCODE_OpReserveReadPipePackets);
	PAIR(THC_SPIRV_OPCODE_OpReserveWritePipePackets);
	PAIR(THC_SPIRV_OPCODE_OpCommitReadPipe);
	PAIR(THC_SPIRV_OPCODE_OpCommitWritePipe);
	PAIR(THC_SPIRV_OPCODE_OpIsValidReserveId);
	PAIR(THC_SPIRV_OPCODE_OpGetNumPipePackets);
	PAIR(THC_SPIRV_OPCODE_OpGetMaxPipePackets);
	PAIR(THC_SPIRV_OPCODE_OpGroupReserveReadPipePackets);
	PAIR(THC_SPIRV_OPCODE_OpGroupReserveWritePipePackets);
	PAIR(THC_SPIRV_OPCODE_OpGroupCommitReadPipe);
	PAIR(THC_SPIRV_OPCODE_OpGroupCommitWritePipe);
	PAIR(THC_SPIRV_OPCODE_OpConstantPipeStorage);
	PAIR(THC_SPIRV_OPCODE_OpCreatePipeFromPipeStorage);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformElect);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformAll);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformAny);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformAllEqual);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBroadcast);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBroadcastFirst);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBallot);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformInverseBallot);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBallotBitExtract);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBallotBitCount);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBallotFindLSB);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBallotFindMSB);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformShuffle);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformShuffleXor);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformShuffleUp);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformShuffleDown);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformIAdd);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformFAdd);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformIMul);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformFMul);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformSMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformUMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformFMin);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformSMax);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformUMax);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformFMax);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseAnd);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseOr);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseXor);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformLogicalAnd);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformLogicalOr);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformLogicalXor);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformQuadBroadcast);
	PAIR(THC_SPIRV_OPCODE_OpGroupNonUniformQuadSwap);

}

bool Visualizer::VisualizeSPIRV(const utils::String& filename) {
	FILE* file = fopen(filename.str, "rb");

	_fseeki64(file, 0, SEEK_END);
	uint64 length = _ftelli64(file);
	_fseeki64(file, 0, SEEK_SET);

	if (length & 0x3) {
		Log::Error("\"%s\" is not 4 byte aligned", filename.str);
		return false;
	}

	List<uint32> code;
	code.Resize(length >> 2);

	fread(code.GetData(), code.GetSize(), 1, file);
	fclose(file);

	return VisualizeSPIRV(code);
}

bool Visualizer::VisualizeSPIRV(List<uint32> code) {
	InitializeOpCodes();



	return false;
}