/*
MIT License

Copyright (c) 2018 Jesper Hammarström

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

//Magic Number
#define THC_SPIRV_MAGIC_NUMBER											0x07230203

//Source Languages
#define THC_SPIRV_SOURCE_LANGUAGE_UNKNOWN								0x0
#define THC_SPIRV_SOURCE_LANGUAGE_ESSL									0x1
#define THC_SPIRV_SOURCE_LANGUAGE_GLSL									0x2
#define THC_SPIRV_SOURCE_LANGUAGE_OPENCL_C								0x3
#define THC_SPIRV_SOURCE_LANGUAGE_OPENCL_CPP							0x4
#define THC_SPIRV_SOURCE_LANGUAGE_HLSL									0x5

//Execution Models
#define THC_SPIRV_EXECUTION_MODEL_VERTEX								0x0
#define THC_SPIRV_EXECUTION_MODEL_TESSELLATION_CONTROL					0x1
#define THC_SPIRV_EXECUTION_MODEL_TESSELLATION_EVALUATION				0x2
#define THC_SPIRV_EXECUTION_MODEL_GEOMETRY								0x3
#define THC_SPIRV_EXECUTION_MODEL_FRAGMENT								0x4
#define THC_SPIRV_EXECUTION_MODEL_GL_COMPUTE							0x5
#define THC_SPIRV_EXECUTION_MODEL_KERNEL								0x6

//Addressing Models
#define THC_SPIRV_ADDRESSING_MODEL_LOGICAL								0x0
#define THC_SPIRV_ADDRESSING_MODEL_PHYSICAL32							0x1
#define THC_SPIRV_ADDRESSING_MODEL_PHYSICAL64							0x2

//Memory Models
#define THC_SPIRV_MEMORY_MODEL_SIMPLE									0x0
#define THC_SPIRV_MEMORY_MODEL_GLSL450									0x1
#define THC_SPIRV_MEMORY_MODEL_OPENCL									0x2

//Executions Modes
#define THC_SPIRV_EXECUTION_MODE_INVOCATIONS							0x00
#define THC_SPIRV_EXECUTION_MODE_SPACING_EQUAL							0x01
#define THC_SPIRV_EXECUTION_MODE_SPACING_FRACTIONAL_EVEN				0x02
#define THC_SPIRV_EXECUTION_MODE_SPACING_FRACTIONAL_ODD					0x03
#define THC_SPIRV_EXECUTION_MODE_VERTEX_ORDER_CW						0x04
#define THC_SPIRV_EXECUTION_MODE_VERTEX_ORDER_CCW						0x05
#define THC_SPIRV_EXECUTION_MODE_PIXEL_CENTER_INTEGER					0x06
#define THC_SPIRV_EXECUTION_MODE_ORIGIN_UPPER_LEFT						0x07
#define THC_SPIRV_EXECUTION_MODE_ORIGIN_LOWER_LEFT						0x08
#define THC_SPIRV_EXECUTION_MODE_EARLY_FRAGMENT_TESTS					0x09
#define THC_SPIRV_EXECUTION_MODE_POINT_MODE								0x0A
#define THC_SPIRV_EXECUTION_MODE_XFB									0x0B
#define THC_SPIRV_EXECUTION_MODE_DEPTH_REPLACING						0x0C
#define THC_SPIRV_EXECUTION_MODE_DEPTH_GREATER							0x0E
#define THC_SPIRV_EXECUTION_MODE_DEPTH_LESS								0x0F
#define THC_SPIRV_EXECUTION_MODE_DEPTH_UNCHANGED						0x10
#define THC_SPIRV_EXECUTION_MODE_LOCAL_SIZE								0x11
#define THC_SPIRV_EXECUTION_MODE_LOCAL_SIZE_HINT						0x12
#define THC_SPIRV_EXECUTION_MODE_INPUT_POINTS							0x13
#define THC_SPIRV_EXECUTION_MODE_INPUT_LINES							0x14
#define THC_SPIRV_EXECUTION_MODE_INPUT_LINES_ADJECENCY					0x15
#define THC_SPIRV_EXECUTION_MODE_TRIANGLES								0x16
#define THC_SPIRV_EXECUTION_MODE_INPUT_TRIANGLES_ADJECENCY				0x17
#define THC_SPIRV_EXECUTION_MODE_QUADS									0x18
#define THC_SPIRV_EXECUTION_MODE_ISOLINES								0x19
#define THC_SPIRV_EXECUTION_MODE_OUTPUT_VERTICES						0x1A
#define THC_SPIRV_EXECUTION_MODE_OUTPUT_POINTS							0x1B
#define THC_SPIRV_EXECUTION_MODE_OUTPUT_LINE_STRIP						0x1C
#define THC_SPIRV_EXECUTION_MODE_OUTPUT_TRIANGLE_STRIP					0x1D
#define THC_SPIRV_EXECUTION_MODE_VEC_TYPE_HINT							0x1E
#define THC_SPIRV_EXECUTION_MODE_CONTRACTION_OFF						0x1F
#define THC_SPIRV_EXECUTION_MODE_INITIALIZER							0x21
#define THC_SPIRV_EXECUTION_MODE_FINALIZER								0x22
#define THC_SPIRV_EXECUTION_MODE_SUB_GROUP_SIZE							0x23
#define THC_SPIRV_EXECUTION_MODE_SUBGROUPS_PER_WORKGROUP				0x24
#define THC_SPIRV_EXECUTION_MODE_SUBGROUPS_PER_WORKGROUP_ID				0x25
#define THC_SPIRV_EXECUTION_MODE_LOCAL_SIZE_ID							0x26
#define THC_SPIRV_EXECUTION_MODE_LOCAL_SIZE_HINT_ID						0x27

//Storage Classes
#define THC_SPIRV_STORAGE_CLASS_UNIFORM_CONSTANT						0x0
#define THC_SPIRV_STORAGE_CLASS_INPUT									0x1
#define THC_SPIRV_STORAGE_CLASS_UNIFORM									0x2
#define THC_SPIRV_STORAGE_CLASS_OUTPUT									0x3
#define THC_SPIRV_STORAGE_CLASS_WORKGROUP								0x4
#define THC_SPIRV_STORAGE_CLASS_CROSS_WORKGROUP							0x5
#define THC_SPIRV_STORAGE_CLASS_PRIVATE									0x6
#define THC_SPIRV_STORAGE_CLASS_FUNCTION								0x7
#define THC_SPIRV_STORAGE_CLASS_GENERIC									0x8
#define THC_SPIRV_STORAGE_CLASS_PUSH_CONSTANT							0x9
#define THC_SPIRV_STORAGE_CLASS_ATOMIC_COUNTER							0xA
#define THC_SPIRV_STORAGE_CLASS_IMAGE									0xB
#define THC_SPIRV_STORAGE_CLASS_STORAGE_BUFFER							0xC

//Dimensions
#define THC_SPIRV_DIMENSIONS_1D											0x0
#define THC_SPIRV_DIMENSIONS_2D											0x1
#define THC_SPIRV_DIMENSIONS_3D											0x2
#define THC_SPIRV_DIMENSIONS_CUBE										0x3
#define THC_SPIRV_DIMENSIONS_RECT										0x4
#define THC_SPIRV_DIMENSIONS_BUFFER										0x5
#define THC_SPIRV_DIMENSIONS_SUBPASS_DATA								0x6

//Sampler Addressing Modes
#define THC_SPIRV_SAMPLER_ADDRESSING_MODE_NONE							0x0
#define THC_SPIRV_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE					0x1
#define THC_SPIRV_SAMPLER_ADDRESSING_MODE_CLAMP							0x2
#define THC_SPIRV_SAMPLER_ADDRESSING_MODE_REPEAT						0x3
#define THC_SPIRV_SAMPLER_ADDRESSING_MODE_REPEAT_MIRRORED				0x4

//Sampler Filter Modes
#define THC_SPIRV_SAMPLER_FILTER_MODE_NEAREST							0x0
#define THC_SPIRV_SAMPLER_FILTER_MODE_LINEAR							0x1

//Image Formats
#define THC_SPIRV_IMAGE_FORMAT_UNKNOWN									0x00
#define THC_SPIRV_IMAGE_FORMAT_RGBA32F									0x01
#define THC_SPIRV_IMAGE_FORMAT_RGBA16F									0x02
#define THC_SPIRV_IMAGE_FORMAT_R32F										0x03
#define THC_SPIRV_IMAGE_FORMAT_RGBA8									0x04
#define THC_SPIRV_IMAGE_FORMAT_RGBA8_SNORM								0x05
#define THC_SPIRV_IMAGE_FORMAT_RG32F									0x06
#define THC_SPIRV_IMAGE_FORMAT_RG16F									0x07
#define THC_SPIRV_IMAGE_FORMAT_R11G11B10F								0x08
#define THC_SPIRV_IMAGE_FORMAT_R16F										0x09
#define THC_SPIRV_IMAGE_FORMAT_RGBA16F									0x0A
#define THC_SPIRV_IMAGE_FORMAT_RGB10A2									0x0B
#define THC_SPIRV_IMAGE_FORMAT_RG16										0x0C
#define THC_SPIRV_IMAGE_FORMAT_RG8										0x0D
#define THC_SPIRV_IMAGE_FORMAT_R16										0x0E
#define THC_SPIRV_IMAGE_FORMAT_R8										0x0F
#define THC_SPIRV_IMAGE_FORMAT_RGBA16_SNORM								0x10
#define THC_SPIRV_IMAGE_FORMAT_RG16_SNORM								0x11
#define THC_SPIRV_IMAGE_FORMAT_RG8_SNORM								0x12
#define THC_SPIRV_IMAGE_FORMAT_R16_SNORM								0x13
#define THC_SPIRV_IMAGE_FORMAT_R8_SNORM									0x14
#define THC_SPIRV_IMAGE_FORMAT_RGBA32I									0x15
#define THC_SPIRV_IMAGE_FORMAT_RGBA16I									0x16
#define THC_SPIRV_IMAGE_FORMAT_RGBA8I									0x17
#define THC_SPIRV_IMAGE_FORMAT_R32I										0x18
#define THC_SPIRV_IMAGE_FORMAT_RG32I									0x19
#define THC_SPIRV_IMAGE_FORMAT_RG16I									0x1A
#define THC_SPIRV_IMAGE_FORMAT_RG8I										0x1B
#define THC_SPIRV_IMAGE_FORMAT_R16I										0x1C
#define THC_SPIRV_IMAGE_FORMAT_R8I										0x1D
#define THC_SPIRV_IMAGE_FORMAT_RGBA32UI									0x1E
#define THC_SPIRV_IMAGE_FORMAT_RGBA16UI									0x1F
#define THC_SPIRV_IMAGE_FORMAT_RGBA8UI									0x20
#define THC_SPIRV_IMAGE_FORMAT_R32UI									0x21
#define THC_SPIRV_IMAGE_FORMAT_RGB10B2UI								0x22
#define THC_SPIRV_IMAGE_FORMAT_RG32UI									0x23
#define THC_SPIRV_IMAGE_FORMAT_RG16UI									0x24
#define THC_SPIRV_IMAGE_FORMAT_RG8UI									0x25
#define THC_SPIRV_IMAGE_FORMAT_R16UI									0x26
#define THC_SPIRV_IMAGE_FORMAT_R8UI										0x27

//Image Channel Orders
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_R									0x00
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_A									0x01
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RG								0x02
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RA								0x03
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RGB								0x04
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RGBA								0x05
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_BGRA								0x06
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_ARGB								0x07
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_INTENSITY							0x08
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_LUMINANCE							0x09
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RX								0x0A
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RGX								0x0B
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_RGBX								0x0C
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_DEPTH								0x0D
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_DEPTH_STENCIL						0x0E
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_SRGB								0x0F
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_SRGBX								0x10
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_SRGBA								0x11
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_SBGRA								0x12
#define THC_SPIRV_IMAGE_CHANNEL_ORDER_ABGR								0x13

//Image Channel Data Types
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_SNORM_INT8					0x00
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_SNORM_INT16					0x01
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_INT8					0x02
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_INT16					0x03
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_SHORT565				0x04
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_SHORT555				0x05
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_INT101010				0x06
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_SIGNED_INT8					0x07
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_SIGNED_INT16					0x08
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_SIGNED_INT32					0x09
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNSIGNED_INT8					0x0A
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNSIGNED_INT16				0x0B
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNSIGNED_INT32				0x0C
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_HALF_FLOAT					0x0D
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_FLOAT							0x0E
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_INT24					0x0F
#define THC_SPIRV_IMAGE_CHANNEL_DATA_TYPE_UNORM_INT101010_2				0x10

//Image Operands
#define THC_SPIRV_IMAGE_OPERAND_NONE									0x00
#define THC_SPIRV_IMAGE_OPERAND_BIAS									0x01
#define THC_SPIRV_IMAGE_OPERAND_LOD										0x02
#define THC_SPIRV_IMAGE_OPERAND_GRAD									0x04
#define THC_SPIRV_IMAGE_OPERAND_CONST_OFFSET							0x08
#define THC_SPIRV_IMAGE_OPERAND_OFFSET									0x10
#define THC_SPIRV_IMAGE_OPERAND_CONST_OFFSETS							0x20
#define THC_SPIRV_IMAGE_OPERAND_SAMPLE									0x40
#define THC_SPIRV_IMAGE_OPERAND_MIN_LOD									0x80

//FP Fast Math Modes
#define THC_SPIRV_FP_FAST_MATH_MODE_NONE								0x00
#define THC_SPIRV_FP_FAST_MATH_MODE_NOT_NAN								0x01
#define THC_SPIRV_FP_FAST_MATH_MODE_NOT_INF								0x02
#define THC_SPIRV_FP_FAST_MATH_MODE_NSZ									0x04
#define THC_SPIRV_FP_FAST_MATH_MODE_ALLOW_RECIP							0x08
#define THC_SPIRV_FP_FAST_MATH_MODE_FAST								0x10

//FP Rounding Modes
#define THC_SPIRV_FP_ROUNDING_MODE_RTE									0x0
#define THC_SPIRV_FP_ROUNDING_MODE_RTZ									0x1
#define THC_SPIRV_FP_ROUNDING_MODE_RTP									0x2
#define THC_SPIRV_FP_ROUNDING_MODE_RTN									0x3

//Linkage type
#define THC_SPIRV_LINKAGE_TYPE_EXPORT									0x0
#define THC_SPIRV_LINKAGE_TYPE_IMPORT									0x1

//Access Qualifiers
#define THC_SPIRV_ACCESS_QUALIFIER_READ_ONLY							0x0
#define THC_SPIRV_ACCESS_QUALIFIER_WRITE_ONLY							0x1
#define THC_SPIRV_ACCESS_QUALIFIER_READ_WRITE							0x2

//Function Paramater Attributes
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_ZEXT						0x0
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_SEXT						0x1
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_BY_VALUE					0x2
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_SRET						0x3
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_NO_ALIAS					0x4
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_NO_CAPTURE				0x5
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_NO_WRITE					0x6
#define THC_SPIRV_FUNCTION_PARAMETER_ATTRIBUTE_NO_READ_WRITE			0x7

//Decorations
#define THC_SPIRV_DECORATION_RELAXED_PRECISION							0x00
#define THC_SPIRV_DECORATION_SPEC_ID									0x01
#define THC_SPIRV_DECORATION_BLOCK										0x02
#define THC_SPIRV_DECORATION_BUFFER_BLOCK								0x03
#define THC_SPIRV_DECORATION_ROW_MAJOR									0x04
#define THC_SPIRV_DECORATION_COL_MAJOR									0x05
#define THC_SPIRV_DECORATION_ARRAY_STRIDE								0x06
#define THC_SPIRV_DECORATION_NATRIX_STRIDE								0x07
#define THC_SPIRV_DECORATION_GLSL_SHARED								0x08
#define THC_SPIRV_DECORATION_GLSL_PACKED								0x09
#define THC_SPIRV_DECORATION_C_PACKED									0x0A
#define THC_SPIRV_DECORATION_BUILTIN									0x0B
#define THC_SPIRV_DECORATION_NO_PERSPECTIVE								0x0D
#define THC_SPIRV_DECORATION_FLAT										0x0E
#define THC_SPIRV_DECORATION_PATH										0x0F
#define THC_SPIRV_DECORATION_CENTEROID									0x10
#define THC_SPIRV_DECORATION_SAMPLE										0x11
#define THC_SPIRV_DECORATION_INVARIANT									0x12
#define THC_SPIRV_DECORATION_RESTRICT									0x13
#define THC_SPIRV_DECORATION_ALIASED									0x14
#define THC_SPIRV_DECORATION_VOLATILE									0x15
#define THC_SPIRV_DECORATION_CONSTANT									0x16
#define THC_SPIRV_DECORATION_COHERENT									0x17
#define THC_SPIRV_DECORATION_NON_WRITABLE								0x18
#define THC_SPIRV_DECORATION_NON_READABLE								0x19
#define THC_SPIRV_DECORATION_UNIFORM									0x1A
#define THC_SPIRV_DECORATION_SATURATED_CONVERSION						0x1C
#define THC_SPIRV_DECORATION_STREAM										0x1D
#define THC_SPIRV_DECORATION_LOCATION									0x1E
#define THC_SPIRV_DECORATION_COMPONENT									0x1F
#define THC_SPIRV_DECORATION_INDEX										0x20
#define THC_SPIRV_DECORATION_BINDING									0x21
#define THC_SPIRV_DECORATION_DESCRIPTORSET								0x22
#define THC_SPIRV_DECORATION_OFFSET										0x23
#define THC_SPIRV_DECORATION_XFB_BUFFER									0x24
#define THC_SPIRV_DECORATION_XFB_STRIDE									0x25
#define THC_SPIRV_DECORATION_FUNCTION_PARAMETER_ATTRIBUTE				0x26
#define THC_SPIRV_DECORATION_FP_ROUND_MODE								0x27
#define THC_SPIRV_DECORATION_FP_FAST_MATH_MODE							0x28
#define THC_SPIRV_DECORATION_LINKAGE_ATTRIBUTES							0x29
#define THC_SPIRV_DECORATION_NO_CONTRACTION								0x2A
#define THC_SPIRV_DECORATION_INPUT_ATTACHMENT_IDNEX						0x2B
#define THC_SPIRV_DECORATION_ALIGNMENT									0x2C
#define THC_SPIRV_DECORATION_MAX_BYTE_OFFSET							0x2D
#define THC_SPIRV_DECORATION_ALIGNMENT_ID								0x2E
#define THC_SPIRV_DECORATION_MAX_BYTE_OFFSET_ID							0x2F

//Builtins
#define THC_SPIRV_BUILTIN_POSITION										0x00
#define THC_SPIRV_BUILTIN_POINT_SIZE									0x01
#define THC_SPIRV_BUILTIN_CLIP_DISTANCE									0x03
#define THC_SPIRV_BUILTIN_CULL_DISTANCE									0x04
#define THC_SPIRV_BUILTIN_VERTEX_ID										0x05
#define THC_SPIRV_BUILTIN_INSTANCE_ID									0x06
#define THC_SPIRV_BUILTIN_PRIMITIVE_ID									0x07
#define THC_SPIRV_BUILTIN_INVOCATION_ID									0x08
#define THC_SPIRV_BUILTIN_LAYER											0x09
#define THC_SPIRV_BUILTIN_VIEWPORT_INDEX								0x0A
#define THC_SPIRV_BUILTIN_TESSELLATION_LEVEL_OUTER						0x0B
#define THC_SPIRV_BUILTIN_TESSELLATION_LEVEL_INNER						0x0C
#define THC_SPIRV_BUILTIN_TESSELLATION_COORD							0x0D
#define THC_SPIRV_BUILTIN_PATCH_VERTICES								0x0E
#define THC_SPIRV_BUILTIN_FRAG_COORD									0x0F
#define THC_SPIRV_BUILTIN_POINT_COORD									0x10
#define THC_SPIRV_BUILTIN_FRONT_FACING									0x11
#define THC_SPIRV_BUILTIN_SAMPLE_ID										0x12
#define THC_SPIRV_BUILTIN_SAMPLE_POSITION								0x13
#define THC_SPIRV_BUILTIN_SAMPLE_MASK									0x14
#define THC_SPIRV_BUILTIN_FRAG_DEPTH									0x16
#define THC_SPIRV_BUILTIN_HELPER_INVOCATION								0x17
#define THC_SPIRV_BUILTIN_NUM_WORKGROUPS								0x18
#define THC_SPIRV_BUILTIN_WORKGROUP_SIZE								0x19
#define THC_SPIRV_BUILTIN_WORKGROUP_ID									0x1A
#define THC_SPIRV_BUILTIN_LOCAL_INVOCATION_ID							0x1B
#define THC_SPIRV_BUILTIN_GLOBAL_INVOCATION_ID							0x1C
#define THC_SPIRV_BUILTIN_LOCAL_INVOCATION_INDEX						0x1D
#define THC_SPIRV_BUILTIN_WORK_DIMENSIONS								0x1E
#define THC_SPIRV_BUILTIN_GLOBAL_SIZE									0x1F
#define THC_SPIRV_BUILTIN_ENQUEUED_WORKGROUP_SIZE						0x20
#define THC_SPIRV_BUILTIN_GLOBAL_OFFSET									0x21
#define THC_SPIRV_BUILTIN_GLOBAL_LINEAR_ID								0x22
#define THC_SPIRV_BUILTIN_SUBGROUP_SIZE									0x24
#define THC_SPIRV_BUILTIN_SUBGROUP_MAX_SIZE								0x25
#define THC_SPIRV_BUILTIN_NUM_SUBGROUPS									0x26
#define THC_SPIRV_BUILTIN_NUM_ENQUEUED_SUBGROUPS						0x27
#define THC_SPIRV_BUILTIN_SUBGROUP_ID									0x28
#define THC_SPIRV_BUILTIN_SUBGROUP_LOCAL_INVOCATION_ID					0x29
#define THC_SPIRV_BUILTIN_VERTEX_INDEX									0x2A
#define THC_SPIRV_BUILTIN_INSTANCE_INDEX								0x2B
#define THC_SPIRV_BUILTIN_SUBGROUP_EQ_MASK								0x1140
#define THC_SPIRV_BUILTIN_SUBGROUP_GE_MASK								0x1141
#define THC_SPIRV_BUILTIN_SUBGROUP_GT_MASK								0x1142
#define THC_SPIRV_BUILTIN_SUBGROUP_LE_MASK								0x1143
#define THC_SPIRV_BUILTIN_SUBGROUP_LT_MASK								0x1144
#define THC_SPIRV_BUILTIN_SUBGROUP_EQ_MASK_KHR							THC_SPIRV_BUILTIN_SUBGROUP_EQ_MASK
#define THC_SPIRV_BUILTIN_SUBGROUP_GE_MASK_KHR							THC_SPIRV_BUILTIN_SUBGROUP_GE_MASK
#define THC_SPIRV_BUILTIN_SUBGROUP_GT_MASK_KHR							THC_SPIRV_BUILTIN_SUBGROUP_GT_MASK
#define THC_SPIRV_BUILTIN_SUBGROUP_LE_MASK_KHR							THC_SPIRV_BUILTIN_SUBGROUP_LE_MASK
#define THC_SPIRV_BUILTIN_SUBGROUP_LT_MASK_KHR							THC_SPIRV_BUILTIN_SUBGROUP_LT_MASK
#define THC_SPIRV_BUILTIN_BASE_VERTEX									0x1148
#define THC_SPIRV_BUILTIN_BASE_INSTANCE									0x1149
#define THC_SPIRV_BUILTIN_DRAW_INDEX									0x114A
#define THC_SPIRV_BUILTIN_DEVICE_INDEX									0x1156
#define THC_SPIRV_BUILTIN_VIEW_INDEX									0x1158

//Selection Controls
#define THC_SPIRV_SELECTION_CONTROL_NONE								0x0
#define THC_SPIRV_SELECTION_CONTROL_FLATTEN								0x1
#define THC_SPIRV_SELECTION_CONTROL_DONT_FLATTEN						0x2

//Loop Controls
#define THC_SPIRV_LOOP_CONTROL_NONE										0x0
#define THC_SPIRV_LOOP_CONTROL_UNROLL									0x1
#define THC_SPIRV_LOOP_CONTROL_DONT_UNROLL								0x2
#define THC_SPIRV_LOOP_CONTROL_DEPENDENCY_INFINITE						0x4
#define THC_SPIRV_LOOP_CONTROL_DEPENDENCY_LENGTH						0x8

//Function Controls
#define THC_SPIRV_FUNCTION_CONTROL_NONE									0x0
#define THC_SPIRV_FUNCTION_CONTROL_INLINE								0x1
#define THC_SPIRV_FUNCTION_CONTROL_DONT_INLINE							0x2
#define THC_SPIRV_FUNCTION_CONTROL_PURE									0x4
#define THC_SPIRV_FUNCTION_CONTROL_CONST								0x8

//Memory Semantics
#define THC_SPIRV_MEMORY_SEMANTIC_NONE									0x000
#define THC_SPIRV_MEMORY_SEMANTIC_ACQUIRE								0x002
#define THC_SPIRV_MEMORY_SEMANTIC_RELEASE								0x004
#define THC_SPIRV_MEMORY_SEMANTIC_ACQUIRE_RELEASE						0x008
#define THC_SPIRV_MEMORY_SEMANTIC_SEQUENTIALLY_CONSISTENT				0x010
#define THC_SPIRV_MEMORY_SEMANTIC_UNIFORM_MEMORY						0x040
#define THC_SPIRV_MEMORY_SEMANTIC_SUBGROUP_MEMORY						0x080
#define THC_SPIRV_MEMORY_SEMANTIC_WORKGROUP_MEMORY						0x100
#define THC_SPIRV_MEMORY_SEMANTIC_CROSS_WORKGROUP_MEMORY				0x200
#define THC_SPIRV_MEMORY_SEMANTIC_ATOMIC_COUNTER_MEMORY					0x400
#define THC_SPIRV_MEMORY_SEMANTIC_IMAGE_MEMORY							0x800

//Memory Access
#define THC_SPIRV_MEMORY_ACCESS_NONE									0x0
#define THC_SPIRV_MEMORY_ACCESS_VOLATILE								0x1
#define THC_SPIRV_MEMORY_ACCESS_ALIGNED									0x2
#define THC_SPIRV_MEMORY_ACCESS_NON_TEMPORAL							0x4

//Scopes	
#define THC_SPIRV_SCOPE_CROSS_DEVICE									0x0
#define THC_SPIRV_SCOPE_DEVICE											0x1
#define THC_SPIRV_SCOPE_WORKGROUP										0x2
#define THC_SPIRV_SCOPE_SUBGROUP										0x3
#define THC_SPIRV_SCOPE_INVOCATION										0x4

//Group Operations
#define THC_SPIRV_GROUP_OPERATION_REDUCE								0x0
#define THC_SPIRV_GROUP_OPERATION_INCLUSIVE_SCAN						0x1
#define THC_SPIRV_GROUP_OPERATION_EXCLUSIVE_SCAN						0x2
#define THC_SPIRV_GROUP_OPERATION_CLUSTERED_REDUCE						0x3

//Kernel Enqueue Flags
#define THC_SPIRV_KERNEL_ENQUEUE_FLAG_NO_WAIT							0x0
#define THC_SPIRV_KERNEL_ENQUEUE_FLAG_WAIT_KERNEL						0x1
#define THC_SPIRV_KERNEL_ENQUEUE_FLAG_WAIT_WORKGROUP					0x2

//Kernel Profiling Info
#define THC_SPIRV_KERNEL_PROFILE_INFO_NONE								0x0
#define THC_SPIRV_KERNEL_PROFILE_INFO_CMD_EXECUTE_TIME					0x1

//Capabilities
#define THC_SPIRV_CAPABILITY_MATRIX										0x00
#define THC_SPIRV_CAPABILITY_SHADER										0x01
#define THC_SPIRV_CAPABILITY_GEOMETRY									0x02
#define THC_SPIRV_CAPABILITY_TESSELLATION								0x03
#define THC_SPIRV_CAPABILITY_ADDRESSES									0x04
#define THC_SPIRV_CAPABILITY_LINKAGE									0x05
#define THC_SPIRV_CAPABILITY_KERNEL										0x06
#define THC_SPIRV_CAPABILITY_VECTOR16									0x07
#define THC_SPIRV_CAPABILITY_FLOAT16_BUFFER								0x08
#define THC_SPIRV_CAPABILITY_FLOAT16									0x09
#define THC_SPIRV_CAPABILITY_FLOAT64									0x0A
#define THC_SPIRV_CAPABILITY_INT64										0x0B
#define THC_SPIRV_CAPABILITY_INT64_ATOMICS								0x0C
#define THC_SPIRV_CAPABILITY_IMAGE_BASICS								0x0D
#define THC_SPIRV_CAPABILITY_IMAGE_READ_WRITE							0x0E
#define THC_SPIRV_CAPABILITY_IMAGE_MIPMAP								0x0F
#define THC_SPIRV_CAPABILITY_PIPES										0x11
#define THC_SPIRV_CAPABILITY_GROUPS										0x12
#define THC_SPIRV_CAPABILITY_DEVICE_ENQUEUE								0x13
#define THC_SPIRV_CAPABILITY_LITERAL_SAMPLER							0x14
#define THC_SPIRV_CAPABILITY_ATOMIC_STORAGE								0x15
#define THC_SPIRV_CAPABILITY_INT16										0x16
#define THC_SPIRV_CAPABILITY_TESSELLATION_POINT_SIZE					0x17
#define THC_SPIRV_CAPABILITY_GEOMETRY_POINT_SIZE						0x18
#define THC_SPIRV_CAPABILITY_IMAGE_GATHER_EXTENDED						0x19
#define THC_SPIRV_CAPABILITY_STORAGE_IMAGE_MULTISAMPLE					0x1B
#define THC_SPIRV_CAPABILITY_UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING		0x1C
#define THC_SPIRV_CAPABILITY_SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING		0x1D
#define THC_SPIRV_CAPABILITY_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING		0x1E
#define THC_SPIRV_CAPABILITY_STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING		0x1F
#define THC_SPIRV_CAPABILITY_CLIP_DISTANCE								0x20
#define THC_SPIRV_CAPABILITY_CULL_DISTANCE								0x21
#define THC_SPIRV_CAPABILITY_IMAGE_CUBE_ARRAY							0x22
#define THC_SPIRV_CAPABILITY_SAMPLED_RATE_SHADING						0x23
#define THC_SPIRV_CAPABILITY_IMAGE_RECT									0x24
#define THC_SPIRV_CAPABILITY_SAMPLED_RECT								0x25
#define THC_SPIRV_CAPABILITY_GENERIC_POINTER							0x26
#define THC_SPIRV_CAPABILITY_INT8										0x27
#define THC_SPIRV_CAPABILITY_INPUT_ATTACHMENT							0x28
#define THC_SPIRV_CAPABILITY_SPARSE_RESIDENCY							0x29
#define THC_SPIRV_CAPABILITY_MIN_LOD									0x2A
#define THC_SPIRV_CAPABILITY_SAMPLED_1D									0x2B
#define THC_SPIRV_CAPABILITY_IMAGE_1D									0x2C
#define THC_SPIRV_CAPABILITY_SAMPLED_CUBE_ARRAY							0x2D
#define THC_SPIRV_CAPABILITY_SAMPLED_BUFFER								0x2E
#define THC_SPIRV_CAPABILITY_IMAGE_BUFFER								0x2F
#define THC_SPIRV_CAPABILITY_IMAGE_MS_ARRAY								0x30
#define THC_SPIRV_CAPABILITY_STORAGE_IMAGE_EXTENDED_FORMATS				0x31
#define THC_SPIRV_CAPABILITY_IMAGE_QUERY								0x32
#define THC_SPIRV_CAPABILITY_DERIVATIVE_CONTROL							0x33
#define THC_SPIRV_CAPABILITY_INTERPOLATION_FUNCTION						0x34
#define THC_SPIRV_CAPABILITY_TRANSFORM_FEEDBACK							0x35
#define THC_SPIRV_CAPABILITY_GEOMETRY_STREAMS							0x36
#define THC_SPIRV_CAPABILITY_STORAGE_IMAGE_READ_WITHOUT_FORMAT			0x37
#define THC_SPIRV_CAPABILITY_STORAGE_IMAGE_WRTITE_WITHOUT_FORMAT		0x38
#define THC_SPIRV_CAPABILITY_MULTI_VIEWPORT								0x39
#define THC_SPIRV_CAPABILITY_SUBGROUP_DISPATCH							0x3A
#define THC_SPIRV_CAPABILITY_NAMED_BARRIER								0x3B
#define THC_SPIRV_CAPABILITY_PIPE_STORAGE								0x3C
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM							0x3D
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFROM_VOTE						0x3E
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFROM_ARITHMETIC				0x3F
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM_BALLOT					0x40
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM_SHUFFLE					0x41
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM_SHUFFLE_RELATIVE			0x42
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM_CLUSTERED				0x43
#define THC_SPIRV_CAPABILITY_GROUP_NON_UNIFORM_QUAD						0x44
#define THC_SPIRV_CAPABILITY_DRAW_PARAMETERS							0x114B
#define THC_SPIRV_CAPABILITY_STORAGE_BUFFER_16BIT_ACCESS				0x1151
#define THC_SPIRV_CAPABILITY_STORAGE_UNIFORM_BUFFER_BLOCK16				THC_SPIRV_CAPABILITY_STORAGE_BUFFER_16BIT_ACCESS
#define THC_SPIRV_CAPABILITY_STORAGE_INPUT_OUTPUT_16					0x1154
#define THC_SPIRV_CAPABILITY_DEVICE_GROUP								0x1155
#define THC_SPIRV_CAPABILITY_MULTI_VIEW									0x1157
#define THC_SPIRV_CAPABILITY_VARIABLE_POINTERS_STORAGE_BUFFER			0x1159
#define THC_SPIRV_CAPABILITY_VARIABLE_POINTERS							0x115A

//OpCodes
#define THC_SPIRV_OPCODE_OpNop 0
#define THC_SPIRV_OPCODE_OpUndef 1
#define THC_SPIRV_OPCODE_OpSizeOf 321
#define THC_SPIRV_OPCODE_OpSourceContinued 2
#define THC_SPIRV_OPCODE_OpSource 3
#define THC_SPIRV_OPCODE_OpSourceExtension 4
#define THC_SPIRV_OPCODE_OpName 5
#define THC_SPIRV_OPCODE_OpMemberName 6
#define THC_SPIRV_OPCODE_OpString 7
#define THC_SPIRV_OPCODE_OpLine 8
#define THC_SPIRV_OPCODE_OpNoLine 317
#define THC_SPIRV_OPCODE_OpDecorate 71
#define THC_SPIRV_OPCODE_OpMemberDecorate 72
#define THC_SPIRV_OPCODE_OpDecorateGroup 73
#define THC_SPIRV_OPCODE_OpGroupDecorate 74
#define THC_SPIRV_OPCODE_OpGroupMemberDecorate 75
#define THC_SPIRV_OPCODE_OpDecorateId 332
#define THC_SPIRV_OPCODE_OpExtension 10
#define THC_SPIRV_OPCODE_OpExtInstImport 11
#define THC_SPIRV_OPCODE_OpExtInst 12
#define THC_SPIRV_OPCODE_OpMemoryModel 14
#define THC_SPIRV_OPCODE_OpEntryPoint 15
#define THC_SPIRV_OPCODE_OpExecutionMode 16
#define THC_SPIRV_OPCODE_OpCapability 17
#define THC_SPIRV_OPCODE_OpExecutionModeId 331
#define THC_SPIRV_OPCODE_OpTypeVoid 19
#define THC_SPIRV_OPCODE_OpTypeBool 20
#define THC_SPIRV_OPCODE_OpTypeInt 21
#define THC_SPIRV_OPCODE_OpTypeFloat 22
#define THC_SPIRV_OPCODE_OpTypeVector 23
#define THC_SPIRV_OPCODE_OpTypeMatrix 24
#define THC_SPIRV_OPCODE_OpTypeImage 25
#define THC_SPIRV_OPCODE_OpTypeSampler 26
#define THC_SPIRV_OPCODE_OpTypeSampledImage 27
#define THC_SPIRV_OPCODE_OpTypeArray 28
#define THC_SPIRV_OPCODE_OpTypeRuntimeArray 29
#define THC_SPIRV_OPCODE_OpTypeStruct 30
#define THC_SPIRV_OPCODE_OpTypeOpaque 31
#define THC_SPIRV_OPCODE_OpTypePointer 32
#define THC_SPIRV_OPCODE_OpTypeFunction 33
#define THC_SPIRV_OPCODE_OpTypeEvent 34
#define THC_SPIRV_OPCODE_OpTypeDeviceEvent 35
#define THC_SPIRV_OPCODE_OpTypeReserveId 36
#define THC_SPIRV_OPCODE_OpTypeQueue 37
#define THC_SPIRV_OPCODE_OpTypePipe 38
#define THC_SPIRV_OPCODE_OpTypeForwardPointer 39
#define THC_SPIRV_OPCODE_OpTypePipeStorage 322
#define THC_SPIRV_OPCODE_OpTypeNamedBarrier 327
#define THC_SPIRV_OPCODE_OpConstantTrue 41
#define THC_SPIRV_OPCODE_OpConstantFalse 42
#define THC_SPIRV_OPCODE_OpConstant 43
#define THC_SPIRV_OPCODE_OpConstantComposite 44
#define THC_SPIRV_OPCODE_OpConstantSampler 45
#define THC_SPIRV_OPCODE_OpConstantNull 46
#define THC_SPIRV_OPCODE_OpSpecConstantTrue 48
#define THC_SPIRV_OPCODE_OpSpecConstantFalse 49
#define THC_SPIRV_OPCODE_OpSpecConstant 50
#define THC_SPIRV_OPCODE_OpSpecConstantComposite 51
#define THC_SPIRV_OPCODE_OpSpecConstantOp 52
#define THC_SPIRV_OPCODE_OpVariable 59
#define THC_SPIRV_OPCODE_OpImageTexelPointer 60
#define THC_SPIRV_OPCODE_OpLoad 61
#define THC_SPIRV_OPCODE_OpStore 62
#define THC_SPIRV_OPCODE_OpCopyMemory 63
#define THC_SPIRV_OPCODE_OpCopyMemorySized 64
#define THC_SPIRV_OPCODE_OpAccessChain 65
#define THC_SPIRV_OPCODE_OpInBoundsAccessChain 66
#define THC_SPIRV_OPCODE_OpPtrAccessChain 67
#define THC_SPIRV_OPCODE_OpArrayLength 68
#define THC_SPIRV_OPCODE_OpGenericPtrMemSemantics 69
#define THC_SPIRV_OPCODE_OpInBoundsPtrAccessChain 70
#define THC_SPIRV_OPCODE_OpFunction 54
#define THC_SPIRV_OPCODE_OpFunctionParameter 55
#define THC_SPIRV_OPCODE_OpFunctionEnd 56
#define THC_SPIRV_OPCODE_OpFunctionCall 57
#define THC_SPIRV_OPCODE_OpSampledImage 86
#define THC_SPIRV_OPCODE_OpImageSampleImplicitLod 87
#define THC_SPIRV_OPCODE_OpImageSampleExplicitLod 88
#define THC_SPIRV_OPCODE_OpImageSampleDrefImplicitLod 89
#define THC_SPIRV_OPCODE_OpImageSampleDrefExplicitLod 90
#define THC_SPIRV_OPCODE_OpImageSampleProjImplicitLod 91
#define THC_SPIRV_OPCODE_OpImageSampleProjExplicitLod 92
#define THC_SPIRV_OPCODE_OpImageSampleProjDrefImplicitLod 93
#define THC_SPIRV_OPCODE_OpImageSampleProjDrefExplicitLod 94
#define THC_SPIRV_OPCODE_OpImageFetch 95
#define THC_SPIRV_OPCODE_OpImageGather 96
#define THC_SPIRV_OPCODE_OpImageDrefGather 97
#define THC_SPIRV_OPCODE_OpImageRead 98
#define THC_SPIRV_OPCODE_OpImageWrite 99
#define THC_SPIRV_OPCODE_OpImage 100
#define THC_SPIRV_OPCODE_OpImageQueryFormat 101
#define THC_SPIRV_OPCODE_OpImageQueryOrder 102
#define THC_SPIRV_OPCODE_OpImageQuerySizeLod 103
#define THC_SPIRV_OPCODE_OpImageQuerySize 104
#define THC_SPIRV_OPCODE_OpImageQueryLod 105
#define THC_SPIRV_OPCODE_OpImageQueryLevels 106
#define THC_SPIRV_OPCODE_OpImageQuerySamples 107
#define THC_SPIRV_OPCODE_OpImageSparseSampleImplicitLod 305
#define THC_SPIRV_OPCODE_OpImageSparseSampleExplicitLod 306
#define THC_SPIRV_OPCODE_OpImageSparseSampleDrefImplicitLod 307
#define THC_SPIRV_OPCODE_OpImageSparseSampleDrefExplicitLod 308
#define THC_SPIRV_OPCODE_OpImageSparseSampleProjImplicitLod 309
#define THC_SPIRV_OPCODE_OpImageSparseSampleProjExplicitLod 310
#define THC_SPIRV_OPCODE_OpImageSparseSampleProjDrefImplicitLod 311
#define THC_SPIRV_OPCODE_OpImageSparseSampleProjDrefExplicitLod 312
#define THC_SPIRV_OPCODE_OpImageSparseFetch 313
#define THC_SPIRV_OPCODE_OpImageSparseGather 314
#define THC_SPIRV_OPCODE_OpImageSparseDrefGather 315
#define THC_SPIRV_OPCODE_OpImageSparseTexelsResident 316
#define THC_SPIRV_OPCODE_OpImageSparseRead 320
#define THC_SPIRV_OPCODE_OpConvertFToU 109
#define THC_SPIRV_OPCODE_OpConvertFToS 110
#define THC_SPIRV_OPCODE_OpConvertSToF 111
#define THC_SPIRV_OPCODE_OpConvertUToF 112
#define THC_SPIRV_OPCODE_OpUConvert 113
#define THC_SPIRV_OPCODE_OpSConvert 114
#define THC_SPIRV_OPCODE_OpFConvert 115
#define THC_SPIRV_OPCODE_OpQuantizeToF16 116
#define THC_SPIRV_OPCODE_OpConvertPtrToU 117
#define THC_SPIRV_OPCODE_OpSatConvertSToU 118
#define THC_SPIRV_OPCODE_OpSatConvertUToS 119
#define THC_SPIRV_OPCODE_OpConvertUToPtr 120
#define THC_SPIRV_OPCODE_OpPtrCastToGeneric 121
#define THC_SPIRV_OPCODE_OpGenericCastToPtr 122
#define THC_SPIRV_OPCODE_OpGenericCastToPtrExplicit 123
#define THC_SPIRV_OPCODE_OpBitcast 124
#define THC_SPIRV_OPCODE_OpVectorExtractDynamic 77
#define THC_SPIRV_OPCODE_OpVectorInsertDynamic 78
#define THC_SPIRV_OPCODE_OpVectorShuffle 79
#define THC_SPIRV_OPCODE_OpCompositeConstruct 80
#define THC_SPIRV_OPCODE_OpCompositeExtract 81
#define THC_SPIRV_OPCODE_OpCompositeInsert 82
#define THC_SPIRV_OPCODE_OpCopyObject 83
#define THC_SPIRV_OPCODE_OpTranspose 84
#define THC_SPIRV_OPCODE_OpSNegate 126
#define THC_SPIRV_OPCODE_OpFNegate 127
#define THC_SPIRV_OPCODE_OpIAdd 128
#define THC_SPIRV_OPCODE_OpFAdd 129
#define THC_SPIRV_OPCODE_OpISub 130
#define THC_SPIRV_OPCODE_OpFSub 131
#define THC_SPIRV_OPCODE_OpIMul 132
#define THC_SPIRV_OPCODE_OpFMul 133
#define THC_SPIRV_OPCODE_OpUDiv 134
#define THC_SPIRV_OPCODE_OpSDiv 135
#define THC_SPIRV_OPCODE_OpFDiv 136
#define THC_SPIRV_OPCODE_OpUMod 137
#define THC_SPIRV_OPCODE_OpSRem 138
#define THC_SPIRV_OPCODE_OpSMod 139
#define THC_SPIRV_OPCODE_OpFRem 140
#define THC_SPIRV_OPCODE_OpFMod 141
#define THC_SPIRV_OPCODE_OpVectorTimesScalar 142
#define THC_SPIRV_OPCODE_OpMatrixTimesScalar 143
#define THC_SPIRV_OPCODE_OpVectorTimesMatrix 144
#define THC_SPIRV_OPCODE_OpMatrixTimesVector 145
#define THC_SPIRV_OPCODE_OpMatrixTimesMatrix 146
#define THC_SPIRV_OPCODE_OpOuterProduct 147
#define THC_SPIRV_OPCODE_OpDot 148
#define THC_SPIRV_OPCODE_OpIAddCarry 149
#define THC_SPIRV_OPCODE_OpISubBorrow 150
#define THC_SPIRV_OPCODE_OpUMulExtended 151
#define THC_SPIRV_OPCODE_OpSMulExtended 152
#define THC_SPIRV_OPCODE_OpShiftRightLogical 194
#define THC_SPIRV_OPCODE_OpShiftRightArithmetic 195
#define THC_SPIRV_OPCODE_OpShiftLeftLogical 196
#define THC_SPIRV_OPCODE_OpBitwiseOr 147
#define THC_SPIRV_OPCODE_OpBitwiseXor 198
#define THC_SPIRV_OPCODE_OpBitwiseAnd 199
#define THC_SPIRV_OPCODE_OpNot 200
#define THC_SPIRV_OPCODE_OpBitFieldInsert 201
#define THC_SPIRV_OPCODE_OpBitFieldSExtract 202
#define THC_SPIRV_OPCODE_OpBitFieldUExtract 203
#define THC_SPIRV_OPCODE_OpBitReverse 204
#define THC_SPIRV_OPCODE_OpBitCount 205
#define THC_SPIRV_OPCODE_OpAny 154
#define THC_SPIRV_OPCODE_OpAll 155
#define THC_SPIRV_OPCODE_OpIsNan 156
#define THC_SPIRV_OPCODE_OpIsInf 157
#define THC_SPIRV_OPCODE_OpIsFinite 158
#define THC_SPIRV_OPCODE_OpIsNormal 159
#define THC_SPIRV_OPCODE_OpSignBitSet 160
#define THC_SPIRV_OPCODE_OpLessOrGreater 161
#define THC_SPIRV_OPCODE_OpOrdered 162
#define THC_SPIRV_OPCODE_OpUnordered 163
#define THC_SPIRV_OPCODE_OpLogicalEqual 164
#define THC_SPIRV_OPCODE_OpLogicalNotEqual 165
#define THC_SPIRV_OPCODE_OpLogicalOr 166
#define THC_SPIRV_OPCODE_OpLogicalAnd 167
#define THC_SPIRV_OPCODE_OpLogicalNot 168
#define THC_SPIRV_OPCODE_OpSelect 169
#define THC_SPIRV_OPCODE_OpIEqual 170
#define THC_SPIRV_OPCODE_OpINotEqual 171
#define THC_SPIRV_OPCODE_OpUGreaterThan 172
#define THC_SPIRV_OPCODE_OpSGreaterThan 173
#define THC_SPIRV_OPCODE_OpUGreaterThanEqual 174
#define THC_SPIRV_OPCODE_OpSGreaterThanEqual 175
#define THC_SPIRV_OPCODE_OpULessThan 176
#define THC_SPIRV_OPCODE_OpSLessThan 177
#define THC_SPIRV_OPCODE_OpULessThanEqual 178
#define THC_SPIRV_OPCODE_OpSLessThanEqual 179
#define THC_SPIRV_OPCODE_OpFOrdEqual 180
#define THC_SPIRV_OPCODE_OpFUnordEqual 181
#define THC_SPIRV_OPCODE_OpFOrdNotEqual 182
#define THC_SPIRV_OPCODE_OpFUnordNotEqual 183
#define THC_SPIRV_OPCODE_OpFOrdLessThan 184
#define THC_SPIRV_OPCODE_OpFUnordLessThan 185
#define THC_SPIRV_OPCODE_OpFOrdGreaterThan 186
#define THC_SPIRV_OPCODE_OpFUnordGreaterThan 187
#define THC_SPIRV_OPCODE_OpFOrdLessThanEqual 188
#define THC_SPIRV_OPCODE_OpFUnordLessThanEqual 189
#define THC_SPIRV_OPCODE_OpFOrdGreaterThanEqual 190
#define THC_SPIRV_OPCODE_OpFUnordGreaterThanEqual 191
#define THC_SPIRV_OPCODE_OpDPdx 207
#define THC_SPIRV_OPCODE_OpDPdy 208
#define THC_SPIRV_OPCODE_OpFwidth 209
#define THC_SPIRV_OPCODE_OpDPdxFine 210
#define THC_SPIRV_OPCODE_OpDPdyFine 211
#define THC_SPIRV_OPCODE_OpFwidthFine 212
#define THC_SPIRV_OPCODE_OpDPdxCoarse 213
#define THC_SPIRV_OPCODE_OpDPdyCoarse 214
#define THC_SPIRV_OPCODE_OpFwidthCoarse 215
#define THC_SPIRV_OPCODE_OpPhi 245
#define THC_SPIRV_OPCODE_OpLoopMerge 246
#define THC_SPIRV_OPCODE_OpSelectionMerge 247
#define THC_SPIRV_OPCODE_OpLabel 248
#define THC_SPIRV_OPCODE_OpBranch 249
#define THC_SPIRV_OPCODE_OpBranchConditional 250
#define THC_SPIRV_OPCODE_OpSwitch 251
#define THC_SPIRV_OPCODE_OpKill 252
#define THC_SPIRV_OPCODE_OpReturn 253
#define THC_SPIRV_OPCODE_OpReturnValue 254
#define THC_SPIRV_OPCODE_OpUnreachable 255
#define THC_SPIRV_OPCODE_OpLifetimeStart 256
#define THC_SPIRV_OPCODE_OpLifetimeStop 257
#define THC_SPIRV_OPCODE_OpAtomicLoad 227
#define THC_SPIRV_OPCODE_OpAtomicStore 228
#define THC_SPIRV_OPCODE_OpAtomicExchange 229
#define THC_SPIRV_OPCODE_OpAtomicCompareExchange 230
#define THC_SPIRV_OPCODE_OpAtomicCompareExchangeWeak 231
#define THC_SPIRV_OPCODE_OpAtomicIIncrement 232
#define THC_SPIRV_OPCODE_OpAtomicIDecrement 233
#define THC_SPIRV_OPCODE_OpAtomicIAdd 234
#define THC_SPIRV_OPCODE_OpAtomicISub 235
#define THC_SPIRV_OPCODE_OpAtomicSMin 236
#define THC_SPIRV_OPCODE_OpAtomicUMin 237
#define THC_SPIRV_OPCODE_OpAtomicSMax 238
#define THC_SPIRV_OPCODE_OpAtomicUMax 239
#define THC_SPIRV_OPCODE_OpAtomicAnd 240
#define THC_SPIRV_OPCODE_OpAtomicOr 241
#define THC_SPIRV_OPCODE_OpAtomicXor 242
#define THC_SPIRV_OPCODE_OpAtomicFlagTestAndSet 318
#define THC_SPIRV_OPCODE_OpAtomicFlagClear 319
#define THC_SPIRV_OPCODE_OpEmitVertex 218
#define THC_SPIRV_OPCODE_OpEndPrimitive 219
#define THC_SPIRV_OPCODE_OpEmitStreamVertex 220
#define THC_SPIRV_OPCODE_OpEndStreamPrimitive 221
#define THC_SPIRV_OPCODE_OpControlBarrier 224
#define THC_SPIRV_OPCODE_OpMemoryBarrier 225
#define THC_SPIRV_OPCODE_OpNamedBarrierInitialize 328
#define THC_SPIRV_OPCODE_OpMemoryNamedBarrier 329
#define THC_SPIRV_OPCODE_OpGroupAsyncCopy 259
#define THC_SPIRV_OPCODE_OpGroupWaitEvents 260
#define THC_SPIRV_OPCODE_OpGroupAll 261
#define THC_SPIRV_OPCODE_OpGroupAny 262
#define THC_SPIRV_OPCODE_OpGroupBroadcast 263
#define THC_SPIRV_OPCODE_OpGroupIAdd 264
#define THC_SPIRV_OPCODE_OpGroupFAdd 265
#define THC_SPIRV_OPCODE_OpGroupFMin 266
#define THC_SPIRV_OPCODE_OpGroupUMin 267
#define THC_SPIRV_OPCODE_OpGroupSMin 268
#define THC_SPIRV_OPCODE_OpGroupFMax 269
#define THC_SPIRV_OPCODE_OpGroupUMax 270
#define THC_SPIRV_OPCODE_OpGroupSMax 271
#define THC_SPIRV_OPCODE_OpEnqueueMarker 291
#define THC_SPIRV_OPCODE_OpEnqueueKernel 292
#define THC_SPIRV_OPCODE_OpGetKernelNDrangeSubGroupCount 293
#define THC_SPIRV_OPCODE_OpGetKernelNDrangeMaxSubGroupSize 295
#define THC_SPIRV_OPCODE_OpGetKernelPreferredWorkGroupSizeMultiple 296
#define THC_SPIRV_OPCODE_OpRetainEvent 297
#define THC_SPIRV_OPCODE_OpReleaseEvent 298
#define THC_SPIRV_OPCODE_OpCreateUserEvent 299
#define THC_SPIRV_OPCODE_OpIsValidEvent 300
#define THC_SPIRV_OPCODE_OpSetUserEventStatus 301
#define THC_SPIRV_OPCODE_OpCaptureEventProfilingInfo 302
#define THC_SPIRV_OPCODE_OpGetDefaultQueue 303
#define THC_SPIRV_OPCODE_OpBuildNDRange 304
#define THC_SPIRV_OPCODE_OpGetKernelLocalSizeForSubgroupCount 325
#define THC_SPIRV_OPCODE_OpGetKernelMaxNumSubgroups 326
#define THC_SPIRV_OPCODE_OpReadPipe 274
#define THC_SPIRV_OPCODE_OpWritePipe 275
#define THC_SPIRV_OPCODE_OpReservedReadPipe 276
#define THC_SPIRV_OPCODE_OpReservedWritePipe 277
#define THC_SPIRV_OPCODE_OpReserveReadPipePackets 278
#define THC_SPIRV_OPCODE_OpReserveWritePipePackets 279
#define THC_SPIRV_OPCODE_OpCommitReadPipe 280
#define THC_SPIRV_OPCODE_OpCommitWritePipe 281
#define THC_SPIRV_OPCODE_OpIsValidReserveId 282
#define THC_SPIRV_OPCODE_OpGetNumPipePackets 283
#define THC_SPIRV_OPCODE_OpGetMaxPipePackets 284
#define THC_SPIRV_OPCODE_OpGroupReserveReadPipePackets 285
#define THC_SPIRV_OPCODE_OpGroupReserveWritePipePackets 286
#define THC_SPIRV_OPCODE_OpGroupCommitReadPipe 287
#define THC_SPIRV_OPCODE_OpGroupCommitWritePipe 288
#define THC_SPIRV_OPCODE_OpConstantPipeStorage 323
#define THC_SPIRV_OPCODE_OpCreatePipeFromPipeStorage 324
#define THC_SPIRV_OPCODE_OpGroupNonUniformElect 333
#define THC_SPIRV_OPCODE_OpGroupNonUniformAll 334
#define THC_SPIRV_OPCODE_OpGroupNonUniformAny 335
#define THC_SPIRV_OPCODE_OpGroupNonUniformAllEqual 336
#define THC_SPIRV_OPCODE_OpGroupNonUniformBroadcast 337
#define THC_SPIRV_OPCODE_OpGroupNonUniformBroadcastFirst 338
#define THC_SPIRV_OPCODE_OpGroupNonUniformBallot 339
#define THC_SPIRV_OPCODE_OpGroupNonUniformInverseBallot 340
#define THC_SPIRV_OPCODE_OpGroupNonUniformBallotBitExtract 341
#define THC_SPIRV_OPCODE_OpGroupNonUniformBallotBitCount 342
#define THC_SPIRV_OPCODE_OpGroupNonUniformBallotFindLSB 343
#define THC_SPIRV_OPCODE_OpGroupNonUniformBallotFindMSB 344
#define THC_SPIRV_OPCODE_OpGroupNonUniformShuffle 345
#define THC_SPIRV_OPCODE_OpGroupNonUniformShuffleXor 346
#define THC_SPIRV_OPCODE_OpGroupNonUniformShuffleUp 347
#define THC_SPIRV_OPCODE_OpGroupNonUniformShuffleDown 348
#define THC_SPIRV_OPCODE_OpGroupNonUniformIAdd 349
#define THC_SPIRV_OPCODE_OpGroupNonUniformFAdd 350
#define THC_SPIRV_OPCODE_OpGroupNonUniformIMul 351
#define THC_SPIRV_OPCODE_OpGroupNonUniformFMul 352
#define THC_SPIRV_OPCODE_OpGroupNonUniformSMin 353
#define THC_SPIRV_OPCODE_OpGroupNonUniformUMin 354
#define THC_SPIRV_OPCODE_OpGroupNonUniformFMin 355
#define THC_SPIRV_OPCODE_OpGroupNonUniformSMax 356
#define THC_SPIRV_OPCODE_OpGroupNonUniformUMax 357
#define THC_SPIRV_OPCODE_OpGroupNonUniformFMax 358
#define THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseAnd 359
#define THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseOr 360
#define THC_SPIRV_OPCODE_OpGroupNonUniformBitwiseXor 361
#define THC_SPIRV_OPCODE_OpGroupNonUniformLogicalAnd 362
#define THC_SPIRV_OPCODE_OpGroupNonUniformLogicalOr 363
#define THC_SPIRV_OPCODE_OpGroupNonUniformLogicalXor 364
#define THC_SPIRV_OPCODE_OpGroupNonUniformQuadBroadcast 364
#define THC_SPIRV_OPCODE_OpGroupNonUniformQuadSwap 366


